# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['app.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('data/', 'data/'),
        ('templates/', 'templates/'),
        ('static/', 'static/'),
        ('docs/', 'docs/'),
    ],
    hiddenimports=[
        'flask',
        'flask_socketio',
        'whoosh',
        'requests',
        'urllib3',
        'certifi',
        'charset_normalizer',
        'idna',
        'docx',
        'PyPDF2',
        'lxml',
        'beautifulsoup4',
        'bs4',
        'openai',
        'markdown',
        'json',
        'datetime',
        'hashlib',
        'difflib',
        'threading',
        'subprocess',
        'werkzeug',
        'python_socketio',
        'python_engineio',
        'ssl',
        'socket',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='QuizBattle_DungeonsOfKnowledge',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)